#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=98
NAME=wancheck
USE_PROCD=1
PROG=/usr/sbin/wan_check_status


start_service(){
return 0
    [ -f "$PROG" ] && {
	procd_open_instance
	procd_set_param command ${PROG}
	procd_set_param respawn
	procd_close_instance
    }
}
stop_service() {
    service_stop ${PROG}
}
restart_service() {
return 0
    service_reload ${PROG}
}
