#!/bin/sh /etc/rc.common

#for test, activate later
START=77

NAME=taskdaemon
USE_PROCD=1
CMD="/usr/sbin/taskdaemon"

start_service() {
        procd_open_instance
        procd_set_param command ${CMD}
        procd_set_param respawn
        procd_close_instance
}

stop_service() {
    service_stop ${CMD}
}

restart_service() {
    service_reload ${CMD}
}
