#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017-2019 The Linux Foundation. All rights reserved.
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

START=00
STOP=95
mount_wifi_fw (){

	local arch

	arch=$1
    	mkdir -p /lib/firmware/$arch/WIFI_FW

	cd  /lib/firmware/$arch && ln -sf WIFI_FW/*.* .
	if [ -f /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature.ini ]; then
		cd /lib/firmware
		ln -sf /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature.ini .
	fi
	. /lib/read_caldata_to_fs.sh
	do_load_ipq4019_board_bin

        #mkdir -p /vendor/firmware
        #mv /lib/firmware/$arch/WIFI_FW/Data.msc /vendor/firmware

}

boot() {
 . /lib/functions/system.sh
	local board=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F/ '{print $1}')
        if [ "$board" == "IPQ807x" ]; then
                mount_wifi_fw "IPQ8074"
	elif [ "$board" == "IPQ6018" ]; then
		mount_wifi_fw "IPQ6018"
	else
		echo "\nInvalid Target"
        fi

}

stop() {
	return 0
}
