driver=nl80211
interface=wl13
#channel=0
logger_syslog=127
logger_syslog_level=2
logger_stdout=127
logger_stdout_level=2
channel=0
ieee80211n=1
ieee80211ac=1
ht_capab=[LDPC][SMPS-DYNAMIC][TX-STBC][RX-STBC-1][MAX-AMSDU-7935][DSSS_CCK-40] [SHORT-GI-40]
vht_capab=[MAX-MPDU-11454][RXLDPC][TX-STBC-2BY1][RX-STBC1][SU-BEAMFORMER][SOUNDING-DIMENSION-2][SU-BEAMFORMEE][BF-ANTENNA-2][MAX-A-MPDU-LEN-EXP7][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN]
hw_mode=g
wmm_enabled=1
dtim_period=1
ignore_broadcast_ssid=1
ctrl_interface=/var/run/hostapd-wifi1
ap_isolate=1
ignore_broadcast_ssid=1
send_probe_response=0
auth_algs=1
wpa=0
wpa_group_rekey=0
wpa_strict_rekey=0
ssid=25c829b1922d3123_miwifi
bridge=br-miot
