driver=nl80211
interface=wl0
#channel=0
logger_syslog=127
logger_syslog_level=2
logger_stdout=127
logger_stdout_level=2
channel=0
ieee80211ac=1
ieee80211n=1
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=0
ht_capab=[LDPC][SMPS-DYNAMIC][TX-STBC][RX-STBC-1][MAX-AMSDU-7935][DSSS_CCK-40] [SHORT-GI-40]
vht_capab=[MAX-MPDU-11454][RXLDPC][SHORT-GI-80][TX-STBC-2BY1][RX-STBC1][SU-BEAMFORMER][SOUNDING-DIMENSION-2][SU-BEAMFORMEE][MAX-A-MPDU-LEN-EXP7][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN]
hw_mode=a
wmm_enabled=1
dtim_period=1
ignore_broadcast_ssid=0
ctrl_interface=/var/run/hostapd-wifi0
send_probe_response=0
wpa_passphrase=13021985
wpa_group_rekey=0
wpa_strict_rekey=0
wpa_ptk_rekey=0
wpa_gmk_rekey=0
auth_algs=1
wpa=3
wpa_pairwise=CCMP TKIP
wpa_group_rekey=0
wpa_strict_rekey=0
pbc_in_m1=1
eap_server=1
wps_state=2
ap_setup_locked=0
device_type=6-0050F204-1
device_name=XiaoMiRouter
manufacturer=xiaomi
model_name=RA67
model_number=0002
serial_number=12345
config_methods=push_button
wps_independent=1
wps_rf_bands=a
uuid=87654321-9abc-def0-1234-28d1275a8f2b
ssid=WAW555
bridge=br-lan
ieee80211w=0
wpa_key_mgmt=WPA-PSK       
